// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8R7PXM9q4SDMBryPKh9EQvnllYS8Deg',
    appId: '1:495376169570:android:927cc739cfb4b34ca62f3b',
    messagingSenderId: '495376169570',
    projectId: 'portfonio-c2d95',
    storageBucket: 'portfonio-c2d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uXq9AWJMdxF773Z8pM-nKqQPSmopTBk',
    appId: '1:495376169570:ios:53b5eebfebea1f78a62f3b',
    messagingSenderId: '495376169570',
    projectId: 'portfonio-c2d95',
    storageBucket: 'portfonio-c2d95.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8uXq9AWJMdxF773Z8pM-nKqQPSmopTBk',
    appId: '1:495376169570:ios:8e8d06f53db47dd9a62f3b',
    messagingSenderId: '495376169570',
    projectId: 'portfonio-c2d95',
    storageBucket: 'portfonio-c2d95.appspot.com',
    iosBundleId: 'com.example.flutterTask.RunnerTests',
  );
}
